config/routes.rb
Rails.application.routes.draw do
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :role)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Esbuild</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <p><%= form.label :name, style: "display: block" %></p>
    <p><%= form.text_field :name %></p>
  </div>

  <div>
    <p><%= form.label :role, style: "display: block" %></p>
    <p><%= form.text_field :role %></p>
  </div>

  <div>
    <p><%= form.submit %></p>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= user.role %>
  </p>

</div>

app/views/users/edit.html.erb
<style>
.myDiv {  
  margin: auto;
  width: 60%;
  border: 0px;
  padding: 10px;
}
</style>

<div class="myDiv">
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>
</div>

app/views/users/index.html copy.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/index.html.erb
<style>
.myDiv {  
  margin: auto;
  width: 60%;
  border: 0px;
  padding: 10px;
}
</style>

<div class="myDiv">
  <p style="color: green"><%= notice %></p>
  <h1>Users</h1>

  <p><%= button_to 'NEW USER', new_user_path, method: :get%></p>

  <table cellspacing ="1" width="50%" align="left" >
    <thead>
      <tr align="left">
        <th width="50px">ID</th>
        <th width="300x">Name</th>
        <th width="150px">Role</th>
        <th width="150px"></th>
      </tr>
    </thead>
      <tbody align="left">    
      <% @users.each do |user| %>    
        <tr>
          <td width="50px"><%= user.id%></td>
          <td width="300px"><%= link_to user.name, user%></td>        
          <td width="150px"><%= user.role %></td>                   
          <td><%= link_to "Delete", user_path(user), data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                    } %>
        </tr>     
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<style>
.myDiv {  
  margin: auto;
  width: 60%;
  border: 0px;
  padding: 10px;
}
</style>

<div class="myDiv">
  <p style="color: green"><%= notice %></p>
  <p><%= button_to "Destroy this user", @user, method: :delete %></p> 

  <%= render @user %>

  <div>
    <%= link_to "Edit this user", edit_user_path(@user) %> |      
    <%= link_to "BACK TO USERS", users_path %>
  </div>
</div>